// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".
#ifndef MAIN_H
#define MAIN_H

#define UNICODE

#ifndef UNICODE
    #error "You need to define UNICODE for this app to compile correctly"
#endif

#define DLG_MAIN        1001
#define IDC_REFRESH     4001
#define IDC_ED          4007
#define IDC_CPU         4009

#define IDR_ICO_MAIN    8001
#define IDR_ICO_PC      8002

#endif
